// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: info.proto

package us.ihmc.aci.ddam;

/**
 * Protobuf type {@code ddam.CPU}
 */
public  final class CPU extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ddam.CPU)
    CPUOrBuilder {
  // Use CPU.newBuilder() to construct.
  private CPU(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CPU() {
    vendor_ = "";
    model_ = "";
    freq_ = 0;
    totalCores_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CPU(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            vendor_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            model_ = s;
            break;
          }
          case 24: {

            freq_ = input.readSInt32();
            break;
          }
          case 32: {

            totalCores_ = input.readSInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return us.ihmc.aci.ddam.InfoProto.internal_static_ddam_CPU_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return us.ihmc.aci.ddam.InfoProto.internal_static_ddam_CPU_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            us.ihmc.aci.ddam.CPU.class, us.ihmc.aci.ddam.CPU.Builder.class);
  }

  public static final int VENDOR_FIELD_NUMBER = 1;
  private volatile java.lang.Object vendor_;
  /**
   * <code>optional string vendor = 1;</code>
   *
   * <pre>
   *the vendor of this CPU
   * </pre>
   */
  public java.lang.String getVendor() {
    java.lang.Object ref = vendor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vendor_ = s;
      return s;
    }
  }
  /**
   * <code>optional string vendor = 1;</code>
   *
   * <pre>
   *the vendor of this CPU
   * </pre>
   */
  public com.google.protobuf.ByteString
      getVendorBytes() {
    java.lang.Object ref = vendor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vendor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODEL_FIELD_NUMBER = 2;
  private volatile java.lang.Object model_;
  /**
   * <code>optional string model = 2;</code>
   *
   * <pre>
   *the model of this CPU
   * </pre>
   */
  public java.lang.String getModel() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      model_ = s;
      return s;
    }
  }
  /**
   * <code>optional string model = 2;</code>
   *
   * <pre>
   *the model of this CPU
   * </pre>
   */
  public com.google.protobuf.ByteString
      getModelBytes() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      model_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FREQ_FIELD_NUMBER = 3;
  private int freq_;
  /**
   * <code>optional sint32 freq = 3;</code>
   *
   * <pre>
   *the frequency at which this CPU operates
   * </pre>
   */
  public int getFreq() {
    return freq_;
  }

  public static final int TOTALCORES_FIELD_NUMBER = 4;
  private int totalCores_;
  /**
   * <code>optional sint32 totalCores = 4;</code>
   *
   * <pre>
   *the total number of cores of this CPU
   * </pre>
   */
  public int getTotalCores() {
    return totalCores_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getVendorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, vendor_);
    }
    if (!getModelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, model_);
    }
    if (freq_ != 0) {
      output.writeSInt32(3, freq_);
    }
    if (totalCores_ != 0) {
      output.writeSInt32(4, totalCores_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getVendorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, vendor_);
    }
    if (!getModelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, model_);
    }
    if (freq_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(3, freq_);
    }
    if (totalCores_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(4, totalCores_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof us.ihmc.aci.ddam.CPU)) {
      return super.equals(obj);
    }
    us.ihmc.aci.ddam.CPU other = (us.ihmc.aci.ddam.CPU) obj;

    boolean result = true;
    result = result && getVendor()
        .equals(other.getVendor());
    result = result && getModel()
        .equals(other.getModel());
    result = result && (getFreq()
        == other.getFreq());
    result = result && (getTotalCores()
        == other.getTotalCores());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + VENDOR_FIELD_NUMBER;
    hash = (53 * hash) + getVendor().hashCode();
    hash = (37 * hash) + MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getModel().hashCode();
    hash = (37 * hash) + FREQ_FIELD_NUMBER;
    hash = (53 * hash) + getFreq();
    hash = (37 * hash) + TOTALCORES_FIELD_NUMBER;
    hash = (53 * hash) + getTotalCores();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static us.ihmc.aci.ddam.CPU parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static us.ihmc.aci.ddam.CPU parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.CPU parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static us.ihmc.aci.ddam.CPU parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.CPU parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static us.ihmc.aci.ddam.CPU parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.CPU parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static us.ihmc.aci.ddam.CPU parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.CPU parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static us.ihmc.aci.ddam.CPU parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(us.ihmc.aci.ddam.CPU prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ddam.CPU}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ddam.CPU)
      us.ihmc.aci.ddam.CPUOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return us.ihmc.aci.ddam.InfoProto.internal_static_ddam_CPU_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return us.ihmc.aci.ddam.InfoProto.internal_static_ddam_CPU_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              us.ihmc.aci.ddam.CPU.class, us.ihmc.aci.ddam.CPU.Builder.class);
    }

    // Construct using us.ihmc.aci.ddam.CPU.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      vendor_ = "";

      model_ = "";

      freq_ = 0;

      totalCores_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return us.ihmc.aci.ddam.InfoProto.internal_static_ddam_CPU_descriptor;
    }

    public us.ihmc.aci.ddam.CPU getDefaultInstanceForType() {
      return us.ihmc.aci.ddam.CPU.getDefaultInstance();
    }

    public us.ihmc.aci.ddam.CPU build() {
      us.ihmc.aci.ddam.CPU result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public us.ihmc.aci.ddam.CPU buildPartial() {
      us.ihmc.aci.ddam.CPU result = new us.ihmc.aci.ddam.CPU(this);
      result.vendor_ = vendor_;
      result.model_ = model_;
      result.freq_ = freq_;
      result.totalCores_ = totalCores_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof us.ihmc.aci.ddam.CPU) {
        return mergeFrom((us.ihmc.aci.ddam.CPU)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(us.ihmc.aci.ddam.CPU other) {
      if (other == us.ihmc.aci.ddam.CPU.getDefaultInstance()) return this;
      if (!other.getVendor().isEmpty()) {
        vendor_ = other.vendor_;
        onChanged();
      }
      if (!other.getModel().isEmpty()) {
        model_ = other.model_;
        onChanged();
      }
      if (other.getFreq() != 0) {
        setFreq(other.getFreq());
      }
      if (other.getTotalCores() != 0) {
        setTotalCores(other.getTotalCores());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      us.ihmc.aci.ddam.CPU parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (us.ihmc.aci.ddam.CPU) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object vendor_ = "";
    /**
     * <code>optional string vendor = 1;</code>
     *
     * <pre>
     *the vendor of this CPU
     * </pre>
     */
    public java.lang.String getVendor() {
      java.lang.Object ref = vendor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vendor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string vendor = 1;</code>
     *
     * <pre>
     *the vendor of this CPU
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVendorBytes() {
      java.lang.Object ref = vendor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vendor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string vendor = 1;</code>
     *
     * <pre>
     *the vendor of this CPU
     * </pre>
     */
    public Builder setVendor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      vendor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string vendor = 1;</code>
     *
     * <pre>
     *the vendor of this CPU
     * </pre>
     */
    public Builder clearVendor() {
      
      vendor_ = getDefaultInstance().getVendor();
      onChanged();
      return this;
    }
    /**
     * <code>optional string vendor = 1;</code>
     *
     * <pre>
     *the vendor of this CPU
     * </pre>
     */
    public Builder setVendorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      vendor_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object model_ = "";
    /**
     * <code>optional string model = 2;</code>
     *
     * <pre>
     *the model of this CPU
     * </pre>
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string model = 2;</code>
     *
     * <pre>
     *the model of this CPU
     * </pre>
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string model = 2;</code>
     *
     * <pre>
     *the model of this CPU
     * </pre>
     */
    public Builder setModel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      model_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string model = 2;</code>
     *
     * <pre>
     *the model of this CPU
     * </pre>
     */
    public Builder clearModel() {
      
      model_ = getDefaultInstance().getModel();
      onChanged();
      return this;
    }
    /**
     * <code>optional string model = 2;</code>
     *
     * <pre>
     *the model of this CPU
     * </pre>
     */
    public Builder setModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      model_ = value;
      onChanged();
      return this;
    }

    private int freq_ ;
    /**
     * <code>optional sint32 freq = 3;</code>
     *
     * <pre>
     *the frequency at which this CPU operates
     * </pre>
     */
    public int getFreq() {
      return freq_;
    }
    /**
     * <code>optional sint32 freq = 3;</code>
     *
     * <pre>
     *the frequency at which this CPU operates
     * </pre>
     */
    public Builder setFreq(int value) {
      
      freq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 freq = 3;</code>
     *
     * <pre>
     *the frequency at which this CPU operates
     * </pre>
     */
    public Builder clearFreq() {
      
      freq_ = 0;
      onChanged();
      return this;
    }

    private int totalCores_ ;
    /**
     * <code>optional sint32 totalCores = 4;</code>
     *
     * <pre>
     *the total number of cores of this CPU
     * </pre>
     */
    public int getTotalCores() {
      return totalCores_;
    }
    /**
     * <code>optional sint32 totalCores = 4;</code>
     *
     * <pre>
     *the total number of cores of this CPU
     * </pre>
     */
    public Builder setTotalCores(int value) {
      
      totalCores_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional sint32 totalCores = 4;</code>
     *
     * <pre>
     *the total number of cores of this CPU
     * </pre>
     */
    public Builder clearTotalCores() {
      
      totalCores_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ddam.CPU)
  }

  // @@protoc_insertion_point(class_scope:ddam.CPU)
  private static final us.ihmc.aci.ddam.CPU DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new us.ihmc.aci.ddam.CPU();
  }

  public static us.ihmc.aci.ddam.CPU getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CPU>
      PARSER = new com.google.protobuf.AbstractParser<CPU>() {
    public CPU parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new CPU(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<CPU> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CPU> getParserForType() {
    return PARSER;
  }

  public us.ihmc.aci.ddam.CPU getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

