// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: topology.proto

package us.ihmc.aci.ddam;

public interface HostOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ddam.Host)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint32 ip = 1;</code>
   *
   * <pre>
   *the IP address of the primary network interface of the host expressed as integer
   * </pre>
   */
  int getIp();

  /**
   * <code>optional string mac = 2;</code>
   *
   * <pre>
   *the MAC address of the primary network interface of the host
   * </pre>
   */
  java.lang.String getMac();
  /**
   * <code>optional string mac = 2;</code>
   *
   * <pre>
   *the MAC address of the primary network interface of the host
   * </pre>
   */
  com.google.protobuf.ByteString
      getMacBytes();

  /**
   * <code>optional string gatewayName = 3;</code>
   *
   * <pre>
   * the name of the gatway for this host
   * </pre>
   */
  java.lang.String getGatewayName();
  /**
   * <code>optional string gatewayName = 3;</code>
   *
   * <pre>
   * the name of the gatway for this host
   * </pre>
   */
  com.google.protobuf.ByteString
      getGatewayNameBytes();

  /**
   * <code>optional bool isDefault = 4;</code>
   *
   * <pre>
   * specifies if the host should be considered as default for this subnet (e.g., default gateway)
   * </pre>
   */
  boolean getIsDefault();
}
