// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic.proto

package us.ihmc.aci.ddam;

public interface MocketSensorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ddam.MocketSensor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional double RTT = 1;</code>
   */
  double getRTT();
}
