// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: info.proto

package us.ihmc.aci.ddam;

public interface NetworkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ddam.Network)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string interfaceName = 1;</code>
   *
   * <pre>
   *the common interface name (O.S. dependent) of this network interface
   * </pre>
   */
  java.lang.String getInterfaceName();
  /**
   * <code>optional string interfaceName = 1;</code>
   *
   * <pre>
   *the common interface name (O.S. dependent) of this network interface
   * </pre>
   */
  com.google.protobuf.ByteString
      getInterfaceNameBytes();

  /**
   * <code>optional string ipAddress = 2;</code>
   *
   * <pre>
   *the ip address of this network interface
   * </pre>
   */
  java.lang.String getIpAddress();
  /**
   * <code>optional string ipAddress = 2;</code>
   *
   * <pre>
   *the ip address of this network interface
   * </pre>
   */
  com.google.protobuf.ByteString
      getIpAddressBytes();

  /**
   * <code>optional string macAddress = 3;</code>
   *
   * <pre>
   *the mac address of this network interface
   * </pre>
   */
  java.lang.String getMacAddress();
  /**
   * <code>optional string macAddress = 3;</code>
   *
   * <pre>
   *the mac address of this network interface
   * </pre>
   */
  com.google.protobuf.ByteString
      getMacAddressBytes();

  /**
   * <code>optional string netmask = 4;</code>
   *
   * <pre>
   *the netmask of this network interface
   * </pre>
   */
  java.lang.String getNetmask();
  /**
   * <code>optional string netmask = 4;</code>
   *
   * <pre>
   *the netmask of this network interface
   * </pre>
   */
  com.google.protobuf.ByteString
      getNetmaskBytes();

  /**
   * <code>optional string broadcast = 5;</code>
   *
   * <pre>
   *the broadcast address of this network interface
   * </pre>
   */
  java.lang.String getBroadcast();
  /**
   * <code>optional string broadcast = 5;</code>
   *
   * <pre>
   *the broadcast address of this network interface
   * </pre>
   */
  com.google.protobuf.ByteString
      getBroadcastBytes();

  /**
   * <code>optional sint64 mtu = 6;</code>
   *
   * <pre>
   *the MTU, maximum transmission unit of this network interface
   * </pre>
   */
  long getMtu();

  /**
   * <code>optional bool isPrimary = 7;</code>
   *
   * <pre>
   *establishes whether this interface should be considered primary by the NodeMon
   * </pre>
   */
  boolean getIsPrimary();
}
