// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: topology.proto

package us.ihmc.aci.ddam;

/**
 * Protobuf type {@code ddam.ReadableHost}
 */
public  final class ReadableHost extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ddam.ReadableHost)
    ReadableHostOrBuilder {
  // Use ReadableHost.newBuilder() to construct.
  private ReadableHost(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ReadableHost() {
    ip_ = "";
    mac_ = "";
    gatewayName_ = "";
    isDefault_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ReadableHost(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            ip_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            mac_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            gatewayName_ = s;
            break;
          }
          case 32: {

            isDefault_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return us.ihmc.aci.ddam.TopologyProto.internal_static_ddam_ReadableHost_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return us.ihmc.aci.ddam.TopologyProto.internal_static_ddam_ReadableHost_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            us.ihmc.aci.ddam.ReadableHost.class, us.ihmc.aci.ddam.ReadableHost.Builder.class);
  }

  public static final int IP_FIELD_NUMBER = 1;
  private volatile java.lang.Object ip_;
  /**
   * <code>optional string ip = 1;</code>
   *
   * <pre>
   *the IP address of the primary network interface of the host expressed as string
   * </pre>
   */
  public java.lang.String getIp() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ip_ = s;
      return s;
    }
  }
  /**
   * <code>optional string ip = 1;</code>
   *
   * <pre>
   *the IP address of the primary network interface of the host expressed as string
   * </pre>
   */
  public com.google.protobuf.ByteString
      getIpBytes() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAC_FIELD_NUMBER = 2;
  private volatile java.lang.Object mac_;
  /**
   * <code>optional string mac = 2;</code>
   *
   * <pre>
   *the MAC address of the primary network interface of the host
   * </pre>
   */
  public java.lang.String getMac() {
    java.lang.Object ref = mac_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mac_ = s;
      return s;
    }
  }
  /**
   * <code>optional string mac = 2;</code>
   *
   * <pre>
   *the MAC address of the primary network interface of the host
   * </pre>
   */
  public com.google.protobuf.ByteString
      getMacBytes() {
    java.lang.Object ref = mac_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mac_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GATEWAYNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object gatewayName_;
  /**
   * <code>optional string gatewayName = 3;</code>
   *
   * <pre>
   * the name of the gatway for this host
   * </pre>
   */
  public java.lang.String getGatewayName() {
    java.lang.Object ref = gatewayName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gatewayName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string gatewayName = 3;</code>
   *
   * <pre>
   * the name of the gatway for this host
   * </pre>
   */
  public com.google.protobuf.ByteString
      getGatewayNameBytes() {
    java.lang.Object ref = gatewayName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gatewayName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISDEFAULT_FIELD_NUMBER = 4;
  private boolean isDefault_;
  /**
   * <code>optional bool isDefault = 4;</code>
   *
   * <pre>
   * specifies if the host should be considered as default for this subnet (e.g., default gateway)    
   * </pre>
   */
  public boolean getIsDefault() {
    return isDefault_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, ip_);
    }
    if (!getMacBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, mac_);
    }
    if (!getGatewayNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, gatewayName_);
    }
    if (isDefault_ != false) {
      output.writeBool(4, isDefault_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, ip_);
    }
    if (!getMacBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, mac_);
    }
    if (!getGatewayNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, gatewayName_);
    }
    if (isDefault_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isDefault_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof us.ihmc.aci.ddam.ReadableHost)) {
      return super.equals(obj);
    }
    us.ihmc.aci.ddam.ReadableHost other = (us.ihmc.aci.ddam.ReadableHost) obj;

    boolean result = true;
    result = result && getIp()
        .equals(other.getIp());
    result = result && getMac()
        .equals(other.getMac());
    result = result && getGatewayName()
        .equals(other.getGatewayName());
    result = result && (getIsDefault()
        == other.getIsDefault());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIp().hashCode();
    hash = (37 * hash) + MAC_FIELD_NUMBER;
    hash = (53 * hash) + getMac().hashCode();
    hash = (37 * hash) + GATEWAYNAME_FIELD_NUMBER;
    hash = (53 * hash) + getGatewayName().hashCode();
    hash = (37 * hash) + ISDEFAULT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsDefault());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static us.ihmc.aci.ddam.ReadableHost parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static us.ihmc.aci.ddam.ReadableHost parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.ReadableHost parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static us.ihmc.aci.ddam.ReadableHost parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.ReadableHost parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static us.ihmc.aci.ddam.ReadableHost parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.ReadableHost parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static us.ihmc.aci.ddam.ReadableHost parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.ReadableHost parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static us.ihmc.aci.ddam.ReadableHost parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(us.ihmc.aci.ddam.ReadableHost prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ddam.ReadableHost}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ddam.ReadableHost)
      us.ihmc.aci.ddam.ReadableHostOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return us.ihmc.aci.ddam.TopologyProto.internal_static_ddam_ReadableHost_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return us.ihmc.aci.ddam.TopologyProto.internal_static_ddam_ReadableHost_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              us.ihmc.aci.ddam.ReadableHost.class, us.ihmc.aci.ddam.ReadableHost.Builder.class);
    }

    // Construct using us.ihmc.aci.ddam.ReadableHost.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      ip_ = "";

      mac_ = "";

      gatewayName_ = "";

      isDefault_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return us.ihmc.aci.ddam.TopologyProto.internal_static_ddam_ReadableHost_descriptor;
    }

    public us.ihmc.aci.ddam.ReadableHost getDefaultInstanceForType() {
      return us.ihmc.aci.ddam.ReadableHost.getDefaultInstance();
    }

    public us.ihmc.aci.ddam.ReadableHost build() {
      us.ihmc.aci.ddam.ReadableHost result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public us.ihmc.aci.ddam.ReadableHost buildPartial() {
      us.ihmc.aci.ddam.ReadableHost result = new us.ihmc.aci.ddam.ReadableHost(this);
      result.ip_ = ip_;
      result.mac_ = mac_;
      result.gatewayName_ = gatewayName_;
      result.isDefault_ = isDefault_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof us.ihmc.aci.ddam.ReadableHost) {
        return mergeFrom((us.ihmc.aci.ddam.ReadableHost)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(us.ihmc.aci.ddam.ReadableHost other) {
      if (other == us.ihmc.aci.ddam.ReadableHost.getDefaultInstance()) return this;
      if (!other.getIp().isEmpty()) {
        ip_ = other.ip_;
        onChanged();
      }
      if (!other.getMac().isEmpty()) {
        mac_ = other.mac_;
        onChanged();
      }
      if (!other.getGatewayName().isEmpty()) {
        gatewayName_ = other.gatewayName_;
        onChanged();
      }
      if (other.getIsDefault() != false) {
        setIsDefault(other.getIsDefault());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      us.ihmc.aci.ddam.ReadableHost parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (us.ihmc.aci.ddam.ReadableHost) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object ip_ = "";
    /**
     * <code>optional string ip = 1;</code>
     *
     * <pre>
     *the IP address of the primary network interface of the host expressed as string
     * </pre>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string ip = 1;</code>
     *
     * <pre>
     *the IP address of the primary network interface of the host expressed as string
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string ip = 1;</code>
     *
     * <pre>
     *the IP address of the primary network interface of the host expressed as string
     * </pre>
     */
    public Builder setIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ip_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string ip = 1;</code>
     *
     * <pre>
     *the IP address of the primary network interface of the host expressed as string
     * </pre>
     */
    public Builder clearIp() {
      
      ip_ = getDefaultInstance().getIp();
      onChanged();
      return this;
    }
    /**
     * <code>optional string ip = 1;</code>
     *
     * <pre>
     *the IP address of the primary network interface of the host expressed as string
     * </pre>
     */
    public Builder setIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ip_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mac_ = "";
    /**
     * <code>optional string mac = 2;</code>
     *
     * <pre>
     *the MAC address of the primary network interface of the host
     * </pre>
     */
    public java.lang.String getMac() {
      java.lang.Object ref = mac_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mac_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string mac = 2;</code>
     *
     * <pre>
     *the MAC address of the primary network interface of the host
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMacBytes() {
      java.lang.Object ref = mac_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string mac = 2;</code>
     *
     * <pre>
     *the MAC address of the primary network interface of the host
     * </pre>
     */
    public Builder setMac(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mac_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string mac = 2;</code>
     *
     * <pre>
     *the MAC address of the primary network interface of the host
     * </pre>
     */
    public Builder clearMac() {
      
      mac_ = getDefaultInstance().getMac();
      onChanged();
      return this;
    }
    /**
     * <code>optional string mac = 2;</code>
     *
     * <pre>
     *the MAC address of the primary network interface of the host
     * </pre>
     */
    public Builder setMacBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mac_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gatewayName_ = "";
    /**
     * <code>optional string gatewayName = 3;</code>
     *
     * <pre>
     * the name of the gatway for this host
     * </pre>
     */
    public java.lang.String getGatewayName() {
      java.lang.Object ref = gatewayName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gatewayName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string gatewayName = 3;</code>
     *
     * <pre>
     * the name of the gatway for this host
     * </pre>
     */
    public com.google.protobuf.ByteString
        getGatewayNameBytes() {
      java.lang.Object ref = gatewayName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gatewayName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string gatewayName = 3;</code>
     *
     * <pre>
     * the name of the gatway for this host
     * </pre>
     */
    public Builder setGatewayName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gatewayName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string gatewayName = 3;</code>
     *
     * <pre>
     * the name of the gatway for this host
     * </pre>
     */
    public Builder clearGatewayName() {
      
      gatewayName_ = getDefaultInstance().getGatewayName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string gatewayName = 3;</code>
     *
     * <pre>
     * the name of the gatway for this host
     * </pre>
     */
    public Builder setGatewayNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gatewayName_ = value;
      onChanged();
      return this;
    }

    private boolean isDefault_ ;
    /**
     * <code>optional bool isDefault = 4;</code>
     *
     * <pre>
     * specifies if the host should be considered as default for this subnet (e.g., default gateway)    
     * </pre>
     */
    public boolean getIsDefault() {
      return isDefault_;
    }
    /**
     * <code>optional bool isDefault = 4;</code>
     *
     * <pre>
     * specifies if the host should be considered as default for this subnet (e.g., default gateway)    
     * </pre>
     */
    public Builder setIsDefault(boolean value) {
      
      isDefault_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool isDefault = 4;</code>
     *
     * <pre>
     * specifies if the host should be considered as default for this subnet (e.g., default gateway)    
     * </pre>
     */
    public Builder clearIsDefault() {
      
      isDefault_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ddam.ReadableHost)
  }

  // @@protoc_insertion_point(class_scope:ddam.ReadableHost)
  private static final us.ihmc.aci.ddam.ReadableHost DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new us.ihmc.aci.ddam.ReadableHost();
  }

  public static us.ihmc.aci.ddam.ReadableHost getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReadableHost>
      PARSER = new com.google.protobuf.AbstractParser<ReadableHost>() {
    public ReadableHost parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new ReadableHost(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<ReadableHost> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReadableHost> getParserForType() {
    return PARSER;
  }

  public us.ihmc.aci.ddam.ReadableHost getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

