// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic.proto

package us.ihmc.aci.ddam;

/**
 * Protobuf type {@code ddam.Stat}
 *
 * <pre>
 *represent an individual measure of bandwidth for a certain 
 *source IP, destination IP,  protocol and port
 *to identify the single Stat in a map, use a string with "protocol:port"
 * </pre>
 */
public  final class Stat extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ddam.Stat)
    StatOrBuilder {
  // Use Stat.newBuilder() to construct.
  private Stat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Stat() {
    protocol_ = "";
    port_ = 0;
    sentFiveSec_ = 0;
    receivedFiveSec_ = 0;
    observedFiveSec_ = 0;
    sentMinute_ = 0;
    receivedMinute_ = 0;
    observedMinute_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Stat(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            protocol_ = s;
            break;
          }
          case 16: {

            port_ = input.readUInt32();
            break;
          }
          case 24: {

            sentFiveSec_ = input.readUInt32();
            break;
          }
          case 32: {

            receivedFiveSec_ = input.readUInt32();
            break;
          }
          case 40: {

            observedFiveSec_ = input.readUInt32();
            break;
          }
          case 48: {

            sentMinute_ = input.readUInt32();
            break;
          }
          case 56: {

            receivedMinute_ = input.readUInt32();
            break;
          }
          case 64: {

            observedMinute_ = input.readUInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return us.ihmc.aci.ddam.TrafficProto.internal_static_ddam_Stat_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return us.ihmc.aci.ddam.TrafficProto.internal_static_ddam_Stat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            us.ihmc.aci.ddam.Stat.class, us.ihmc.aci.ddam.Stat.Builder.class);
  }

  public static final int PROTOCOL_FIELD_NUMBER = 1;
  private volatile java.lang.Object protocol_;
  /**
   * <code>optional string protocol = 1;</code>
   *
   * <pre>
   *protocol used
   * </pre>
   */
  public java.lang.String getProtocol() {
    java.lang.Object ref = protocol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      protocol_ = s;
      return s;
    }
  }
  /**
   * <code>optional string protocol = 1;</code>
   *
   * <pre>
   *protocol used
   * </pre>
   */
  public com.google.protobuf.ByteString
      getProtocolBytes() {
    java.lang.Object ref = protocol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      protocol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORT_FIELD_NUMBER = 2;
  private int port_;
  /**
   * <code>optional uint32 port = 2;</code>
   *
   * <pre>
   *destination port
   * </pre>
   */
  public int getPort() {
    return port_;
  }

  public static final int SENTFIVESEC_FIELD_NUMBER = 3;
  private int sentFiveSec_;
  /**
   * <code>optional uint32 sentFiveSec = 3;</code>
   *
   * <pre>
   *average bandwidth in the last 5 seconds (sent)
   * </pre>
   */
  public int getSentFiveSec() {
    return sentFiveSec_;
  }

  public static final int RECEIVEDFIVESEC_FIELD_NUMBER = 4;
  private int receivedFiveSec_;
  /**
   * <code>optional uint32 receivedFiveSec = 4;</code>
   *
   * <pre>
   *average bandwidth in the last 5 seconds (received)
   * </pre>
   */
  public int getReceivedFiveSec() {
    return receivedFiveSec_;
  }

  public static final int OBSERVEDFIVESEC_FIELD_NUMBER = 5;
  private int observedFiveSec_;
  /**
   * <code>optional uint32 observedFiveSec = 5;</code>
   *
   * <pre>
   *average bandwidth in the last 5 seconds (observed)
   * </pre>
   */
  public int getObservedFiveSec() {
    return observedFiveSec_;
  }

  public static final int SENTMINUTE_FIELD_NUMBER = 6;
  private int sentMinute_;
  /**
   * <code>optional uint32 sentMinute = 6;</code>
   *
   * <pre>
   *average bandwidth in the last minute (sent)
   * </pre>
   */
  public int getSentMinute() {
    return sentMinute_;
  }

  public static final int RECEIVEDMINUTE_FIELD_NUMBER = 7;
  private int receivedMinute_;
  /**
   * <code>optional uint32 receivedMinute = 7;</code>
   *
   * <pre>
   *average bandwidth in the last minute (received)
   * </pre>
   */
  public int getReceivedMinute() {
    return receivedMinute_;
  }

  public static final int OBSERVEDMINUTE_FIELD_NUMBER = 8;
  private int observedMinute_;
  /**
   * <code>optional uint32 observedMinute = 8;</code>
   *
   * <pre>
   *average bandwidth in the last minute (observed)
   * </pre>
   */
  public int getObservedMinute() {
    return observedMinute_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getProtocolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, protocol_);
    }
    if (port_ != 0) {
      output.writeUInt32(2, port_);
    }
    if (sentFiveSec_ != 0) {
      output.writeUInt32(3, sentFiveSec_);
    }
    if (receivedFiveSec_ != 0) {
      output.writeUInt32(4, receivedFiveSec_);
    }
    if (observedFiveSec_ != 0) {
      output.writeUInt32(5, observedFiveSec_);
    }
    if (sentMinute_ != 0) {
      output.writeUInt32(6, sentMinute_);
    }
    if (receivedMinute_ != 0) {
      output.writeUInt32(7, receivedMinute_);
    }
    if (observedMinute_ != 0) {
      output.writeUInt32(8, observedMinute_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getProtocolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, protocol_);
    }
    if (port_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, port_);
    }
    if (sentFiveSec_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, sentFiveSec_);
    }
    if (receivedFiveSec_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, receivedFiveSec_);
    }
    if (observedFiveSec_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, observedFiveSec_);
    }
    if (sentMinute_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, sentMinute_);
    }
    if (receivedMinute_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, receivedMinute_);
    }
    if (observedMinute_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, observedMinute_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof us.ihmc.aci.ddam.Stat)) {
      return super.equals(obj);
    }
    us.ihmc.aci.ddam.Stat other = (us.ihmc.aci.ddam.Stat) obj;

    boolean result = true;
    result = result && getProtocol()
        .equals(other.getProtocol());
    result = result && (getPort()
        == other.getPort());
    result = result && (getSentFiveSec()
        == other.getSentFiveSec());
    result = result && (getReceivedFiveSec()
        == other.getReceivedFiveSec());
    result = result && (getObservedFiveSec()
        == other.getObservedFiveSec());
    result = result && (getSentMinute()
        == other.getSentMinute());
    result = result && (getReceivedMinute()
        == other.getReceivedMinute());
    result = result && (getObservedMinute()
        == other.getObservedMinute());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
    hash = (53 * hash) + getProtocol().hashCode();
    hash = (37 * hash) + PORT_FIELD_NUMBER;
    hash = (53 * hash) + getPort();
    hash = (37 * hash) + SENTFIVESEC_FIELD_NUMBER;
    hash = (53 * hash) + getSentFiveSec();
    hash = (37 * hash) + RECEIVEDFIVESEC_FIELD_NUMBER;
    hash = (53 * hash) + getReceivedFiveSec();
    hash = (37 * hash) + OBSERVEDFIVESEC_FIELD_NUMBER;
    hash = (53 * hash) + getObservedFiveSec();
    hash = (37 * hash) + SENTMINUTE_FIELD_NUMBER;
    hash = (53 * hash) + getSentMinute();
    hash = (37 * hash) + RECEIVEDMINUTE_FIELD_NUMBER;
    hash = (53 * hash) + getReceivedMinute();
    hash = (37 * hash) + OBSERVEDMINUTE_FIELD_NUMBER;
    hash = (53 * hash) + getObservedMinute();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static us.ihmc.aci.ddam.Stat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static us.ihmc.aci.ddam.Stat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.Stat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static us.ihmc.aci.ddam.Stat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.Stat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static us.ihmc.aci.ddam.Stat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.Stat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static us.ihmc.aci.ddam.Stat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.Stat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static us.ihmc.aci.ddam.Stat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(us.ihmc.aci.ddam.Stat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ddam.Stat}
   *
   * <pre>
   *represent an individual measure of bandwidth for a certain 
   *source IP, destination IP,  protocol and port
   *to identify the single Stat in a map, use a string with "protocol:port"
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ddam.Stat)
      us.ihmc.aci.ddam.StatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return us.ihmc.aci.ddam.TrafficProto.internal_static_ddam_Stat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return us.ihmc.aci.ddam.TrafficProto.internal_static_ddam_Stat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              us.ihmc.aci.ddam.Stat.class, us.ihmc.aci.ddam.Stat.Builder.class);
    }

    // Construct using us.ihmc.aci.ddam.Stat.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      protocol_ = "";

      port_ = 0;

      sentFiveSec_ = 0;

      receivedFiveSec_ = 0;

      observedFiveSec_ = 0;

      sentMinute_ = 0;

      receivedMinute_ = 0;

      observedMinute_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return us.ihmc.aci.ddam.TrafficProto.internal_static_ddam_Stat_descriptor;
    }

    public us.ihmc.aci.ddam.Stat getDefaultInstanceForType() {
      return us.ihmc.aci.ddam.Stat.getDefaultInstance();
    }

    public us.ihmc.aci.ddam.Stat build() {
      us.ihmc.aci.ddam.Stat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public us.ihmc.aci.ddam.Stat buildPartial() {
      us.ihmc.aci.ddam.Stat result = new us.ihmc.aci.ddam.Stat(this);
      result.protocol_ = protocol_;
      result.port_ = port_;
      result.sentFiveSec_ = sentFiveSec_;
      result.receivedFiveSec_ = receivedFiveSec_;
      result.observedFiveSec_ = observedFiveSec_;
      result.sentMinute_ = sentMinute_;
      result.receivedMinute_ = receivedMinute_;
      result.observedMinute_ = observedMinute_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof us.ihmc.aci.ddam.Stat) {
        return mergeFrom((us.ihmc.aci.ddam.Stat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(us.ihmc.aci.ddam.Stat other) {
      if (other == us.ihmc.aci.ddam.Stat.getDefaultInstance()) return this;
      if (!other.getProtocol().isEmpty()) {
        protocol_ = other.protocol_;
        onChanged();
      }
      if (other.getPort() != 0) {
        setPort(other.getPort());
      }
      if (other.getSentFiveSec() != 0) {
        setSentFiveSec(other.getSentFiveSec());
      }
      if (other.getReceivedFiveSec() != 0) {
        setReceivedFiveSec(other.getReceivedFiveSec());
      }
      if (other.getObservedFiveSec() != 0) {
        setObservedFiveSec(other.getObservedFiveSec());
      }
      if (other.getSentMinute() != 0) {
        setSentMinute(other.getSentMinute());
      }
      if (other.getReceivedMinute() != 0) {
        setReceivedMinute(other.getReceivedMinute());
      }
      if (other.getObservedMinute() != 0) {
        setObservedMinute(other.getObservedMinute());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      us.ihmc.aci.ddam.Stat parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (us.ihmc.aci.ddam.Stat) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object protocol_ = "";
    /**
     * <code>optional string protocol = 1;</code>
     *
     * <pre>
     *protocol used
     * </pre>
     */
    public java.lang.String getProtocol() {
      java.lang.Object ref = protocol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        protocol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string protocol = 1;</code>
     *
     * <pre>
     *protocol used
     * </pre>
     */
    public com.google.protobuf.ByteString
        getProtocolBytes() {
      java.lang.Object ref = protocol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string protocol = 1;</code>
     *
     * <pre>
     *protocol used
     * </pre>
     */
    public Builder setProtocol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      protocol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string protocol = 1;</code>
     *
     * <pre>
     *protocol used
     * </pre>
     */
    public Builder clearProtocol() {
      
      protocol_ = getDefaultInstance().getProtocol();
      onChanged();
      return this;
    }
    /**
     * <code>optional string protocol = 1;</code>
     *
     * <pre>
     *protocol used
     * </pre>
     */
    public Builder setProtocolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      protocol_ = value;
      onChanged();
      return this;
    }

    private int port_ ;
    /**
     * <code>optional uint32 port = 2;</code>
     *
     * <pre>
     *destination port
     * </pre>
     */
    public int getPort() {
      return port_;
    }
    /**
     * <code>optional uint32 port = 2;</code>
     *
     * <pre>
     *destination port
     * </pre>
     */
    public Builder setPort(int value) {
      
      port_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 port = 2;</code>
     *
     * <pre>
     *destination port
     * </pre>
     */
    public Builder clearPort() {
      
      port_ = 0;
      onChanged();
      return this;
    }

    private int sentFiveSec_ ;
    /**
     * <code>optional uint32 sentFiveSec = 3;</code>
     *
     * <pre>
     *average bandwidth in the last 5 seconds (sent)
     * </pre>
     */
    public int getSentFiveSec() {
      return sentFiveSec_;
    }
    /**
     * <code>optional uint32 sentFiveSec = 3;</code>
     *
     * <pre>
     *average bandwidth in the last 5 seconds (sent)
     * </pre>
     */
    public Builder setSentFiveSec(int value) {
      
      sentFiveSec_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 sentFiveSec = 3;</code>
     *
     * <pre>
     *average bandwidth in the last 5 seconds (sent)
     * </pre>
     */
    public Builder clearSentFiveSec() {
      
      sentFiveSec_ = 0;
      onChanged();
      return this;
    }

    private int receivedFiveSec_ ;
    /**
     * <code>optional uint32 receivedFiveSec = 4;</code>
     *
     * <pre>
     *average bandwidth in the last 5 seconds (received)
     * </pre>
     */
    public int getReceivedFiveSec() {
      return receivedFiveSec_;
    }
    /**
     * <code>optional uint32 receivedFiveSec = 4;</code>
     *
     * <pre>
     *average bandwidth in the last 5 seconds (received)
     * </pre>
     */
    public Builder setReceivedFiveSec(int value) {
      
      receivedFiveSec_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 receivedFiveSec = 4;</code>
     *
     * <pre>
     *average bandwidth in the last 5 seconds (received)
     * </pre>
     */
    public Builder clearReceivedFiveSec() {
      
      receivedFiveSec_ = 0;
      onChanged();
      return this;
    }

    private int observedFiveSec_ ;
    /**
     * <code>optional uint32 observedFiveSec = 5;</code>
     *
     * <pre>
     *average bandwidth in the last 5 seconds (observed)
     * </pre>
     */
    public int getObservedFiveSec() {
      return observedFiveSec_;
    }
    /**
     * <code>optional uint32 observedFiveSec = 5;</code>
     *
     * <pre>
     *average bandwidth in the last 5 seconds (observed)
     * </pre>
     */
    public Builder setObservedFiveSec(int value) {
      
      observedFiveSec_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 observedFiveSec = 5;</code>
     *
     * <pre>
     *average bandwidth in the last 5 seconds (observed)
     * </pre>
     */
    public Builder clearObservedFiveSec() {
      
      observedFiveSec_ = 0;
      onChanged();
      return this;
    }

    private int sentMinute_ ;
    /**
     * <code>optional uint32 sentMinute = 6;</code>
     *
     * <pre>
     *average bandwidth in the last minute (sent)
     * </pre>
     */
    public int getSentMinute() {
      return sentMinute_;
    }
    /**
     * <code>optional uint32 sentMinute = 6;</code>
     *
     * <pre>
     *average bandwidth in the last minute (sent)
     * </pre>
     */
    public Builder setSentMinute(int value) {
      
      sentMinute_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 sentMinute = 6;</code>
     *
     * <pre>
     *average bandwidth in the last minute (sent)
     * </pre>
     */
    public Builder clearSentMinute() {
      
      sentMinute_ = 0;
      onChanged();
      return this;
    }

    private int receivedMinute_ ;
    /**
     * <code>optional uint32 receivedMinute = 7;</code>
     *
     * <pre>
     *average bandwidth in the last minute (received)
     * </pre>
     */
    public int getReceivedMinute() {
      return receivedMinute_;
    }
    /**
     * <code>optional uint32 receivedMinute = 7;</code>
     *
     * <pre>
     *average bandwidth in the last minute (received)
     * </pre>
     */
    public Builder setReceivedMinute(int value) {
      
      receivedMinute_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 receivedMinute = 7;</code>
     *
     * <pre>
     *average bandwidth in the last minute (received)
     * </pre>
     */
    public Builder clearReceivedMinute() {
      
      receivedMinute_ = 0;
      onChanged();
      return this;
    }

    private int observedMinute_ ;
    /**
     * <code>optional uint32 observedMinute = 8;</code>
     *
     * <pre>
     *average bandwidth in the last minute (observed)
     * </pre>
     */
    public int getObservedMinute() {
      return observedMinute_;
    }
    /**
     * <code>optional uint32 observedMinute = 8;</code>
     *
     * <pre>
     *average bandwidth in the last minute (observed)
     * </pre>
     */
    public Builder setObservedMinute(int value) {
      
      observedMinute_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 observedMinute = 8;</code>
     *
     * <pre>
     *average bandwidth in the last minute (observed)
     * </pre>
     */
    public Builder clearObservedMinute() {
      
      observedMinute_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ddam.Stat)
  }

  // @@protoc_insertion_point(class_scope:ddam.Stat)
  private static final us.ihmc.aci.ddam.Stat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new us.ihmc.aci.ddam.Stat();
  }

  public static us.ihmc.aci.ddam.Stat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Stat>
      PARSER = new com.google.protobuf.AbstractParser<Stat>() {
    public Stat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new Stat(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<Stat> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Stat> getParserForType() {
    return PARSER;
  }

  public us.ihmc.aci.ddam.Stat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

