// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qos.proto

package us.ihmc.aci.ddam;

/**
 * Protobuf type {@code ddam.TagList}
 */
public  final class TagList extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ddam.TagList)
    TagListOrBuilder {
  // Use TagList.newBuilder() to construct.
  private TagList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TagList() {
    qosTags_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TagList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              qosTags_ = new java.util.ArrayList<us.ihmc.aci.ddam.TaggedQoS>();
              mutable_bitField0_ |= 0x00000001;
            }
            qosTags_.add(input.readMessage(us.ihmc.aci.ddam.TaggedQoS.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        qosTags_ = java.util.Collections.unmodifiableList(qosTags_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return us.ihmc.aci.ddam.QoSProto.internal_static_ddam_TagList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return us.ihmc.aci.ddam.QoSProto.internal_static_ddam_TagList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            us.ihmc.aci.ddam.TagList.class, us.ihmc.aci.ddam.TagList.Builder.class);
  }

  public static final int QOSTAGS_FIELD_NUMBER = 1;
  private java.util.List<us.ihmc.aci.ddam.TaggedQoS> qosTags_;
  /**
   * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
   *
   * <pre>
   *list of tags with the associated QoS
   * </pre>
   */
  public java.util.List<us.ihmc.aci.ddam.TaggedQoS> getQosTagsList() {
    return qosTags_;
  }
  /**
   * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
   *
   * <pre>
   *list of tags with the associated QoS
   * </pre>
   */
  public java.util.List<? extends us.ihmc.aci.ddam.TaggedQoSOrBuilder> 
      getQosTagsOrBuilderList() {
    return qosTags_;
  }
  /**
   * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
   *
   * <pre>
   *list of tags with the associated QoS
   * </pre>
   */
  public int getQosTagsCount() {
    return qosTags_.size();
  }
  /**
   * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
   *
   * <pre>
   *list of tags with the associated QoS
   * </pre>
   */
  public us.ihmc.aci.ddam.TaggedQoS getQosTags(int index) {
    return qosTags_.get(index);
  }
  /**
   * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
   *
   * <pre>
   *list of tags with the associated QoS
   * </pre>
   */
  public us.ihmc.aci.ddam.TaggedQoSOrBuilder getQosTagsOrBuilder(
      int index) {
    return qosTags_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < qosTags_.size(); i++) {
      output.writeMessage(1, qosTags_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < qosTags_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, qosTags_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof us.ihmc.aci.ddam.TagList)) {
      return super.equals(obj);
    }
    us.ihmc.aci.ddam.TagList other = (us.ihmc.aci.ddam.TagList) obj;

    boolean result = true;
    result = result && getQosTagsList()
        .equals(other.getQosTagsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getQosTagsCount() > 0) {
      hash = (37 * hash) + QOSTAGS_FIELD_NUMBER;
      hash = (53 * hash) + getQosTagsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static us.ihmc.aci.ddam.TagList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static us.ihmc.aci.ddam.TagList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.TagList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static us.ihmc.aci.ddam.TagList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.TagList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static us.ihmc.aci.ddam.TagList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.TagList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static us.ihmc.aci.ddam.TagList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.TagList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static us.ihmc.aci.ddam.TagList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(us.ihmc.aci.ddam.TagList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ddam.TagList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ddam.TagList)
      us.ihmc.aci.ddam.TagListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return us.ihmc.aci.ddam.QoSProto.internal_static_ddam_TagList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return us.ihmc.aci.ddam.QoSProto.internal_static_ddam_TagList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              us.ihmc.aci.ddam.TagList.class, us.ihmc.aci.ddam.TagList.Builder.class);
    }

    // Construct using us.ihmc.aci.ddam.TagList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getQosTagsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (qosTagsBuilder_ == null) {
        qosTags_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        qosTagsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return us.ihmc.aci.ddam.QoSProto.internal_static_ddam_TagList_descriptor;
    }

    public us.ihmc.aci.ddam.TagList getDefaultInstanceForType() {
      return us.ihmc.aci.ddam.TagList.getDefaultInstance();
    }

    public us.ihmc.aci.ddam.TagList build() {
      us.ihmc.aci.ddam.TagList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public us.ihmc.aci.ddam.TagList buildPartial() {
      us.ihmc.aci.ddam.TagList result = new us.ihmc.aci.ddam.TagList(this);
      int from_bitField0_ = bitField0_;
      if (qosTagsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          qosTags_ = java.util.Collections.unmodifiableList(qosTags_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.qosTags_ = qosTags_;
      } else {
        result.qosTags_ = qosTagsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof us.ihmc.aci.ddam.TagList) {
        return mergeFrom((us.ihmc.aci.ddam.TagList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(us.ihmc.aci.ddam.TagList other) {
      if (other == us.ihmc.aci.ddam.TagList.getDefaultInstance()) return this;
      if (qosTagsBuilder_ == null) {
        if (!other.qosTags_.isEmpty()) {
          if (qosTags_.isEmpty()) {
            qosTags_ = other.qosTags_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureQosTagsIsMutable();
            qosTags_.addAll(other.qosTags_);
          }
          onChanged();
        }
      } else {
        if (!other.qosTags_.isEmpty()) {
          if (qosTagsBuilder_.isEmpty()) {
            qosTagsBuilder_.dispose();
            qosTagsBuilder_ = null;
            qosTags_ = other.qosTags_;
            bitField0_ = (bitField0_ & ~0x00000001);
            qosTagsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getQosTagsFieldBuilder() : null;
          } else {
            qosTagsBuilder_.addAllMessages(other.qosTags_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      us.ihmc.aci.ddam.TagList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (us.ihmc.aci.ddam.TagList) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<us.ihmc.aci.ddam.TaggedQoS> qosTags_ =
      java.util.Collections.emptyList();
    private void ensureQosTagsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        qosTags_ = new java.util.ArrayList<us.ihmc.aci.ddam.TaggedQoS>(qosTags_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        us.ihmc.aci.ddam.TaggedQoS, us.ihmc.aci.ddam.TaggedQoS.Builder, us.ihmc.aci.ddam.TaggedQoSOrBuilder> qosTagsBuilder_;

    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public java.util.List<us.ihmc.aci.ddam.TaggedQoS> getQosTagsList() {
      if (qosTagsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(qosTags_);
      } else {
        return qosTagsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public int getQosTagsCount() {
      if (qosTagsBuilder_ == null) {
        return qosTags_.size();
      } else {
        return qosTagsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public us.ihmc.aci.ddam.TaggedQoS getQosTags(int index) {
      if (qosTagsBuilder_ == null) {
        return qosTags_.get(index);
      } else {
        return qosTagsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public Builder setQosTags(
        int index, us.ihmc.aci.ddam.TaggedQoS value) {
      if (qosTagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQosTagsIsMutable();
        qosTags_.set(index, value);
        onChanged();
      } else {
        qosTagsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public Builder setQosTags(
        int index, us.ihmc.aci.ddam.TaggedQoS.Builder builderForValue) {
      if (qosTagsBuilder_ == null) {
        ensureQosTagsIsMutable();
        qosTags_.set(index, builderForValue.build());
        onChanged();
      } else {
        qosTagsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public Builder addQosTags(us.ihmc.aci.ddam.TaggedQoS value) {
      if (qosTagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQosTagsIsMutable();
        qosTags_.add(value);
        onChanged();
      } else {
        qosTagsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public Builder addQosTags(
        int index, us.ihmc.aci.ddam.TaggedQoS value) {
      if (qosTagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQosTagsIsMutable();
        qosTags_.add(index, value);
        onChanged();
      } else {
        qosTagsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public Builder addQosTags(
        us.ihmc.aci.ddam.TaggedQoS.Builder builderForValue) {
      if (qosTagsBuilder_ == null) {
        ensureQosTagsIsMutable();
        qosTags_.add(builderForValue.build());
        onChanged();
      } else {
        qosTagsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public Builder addQosTags(
        int index, us.ihmc.aci.ddam.TaggedQoS.Builder builderForValue) {
      if (qosTagsBuilder_ == null) {
        ensureQosTagsIsMutable();
        qosTags_.add(index, builderForValue.build());
        onChanged();
      } else {
        qosTagsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public Builder addAllQosTags(
        java.lang.Iterable<? extends us.ihmc.aci.ddam.TaggedQoS> values) {
      if (qosTagsBuilder_ == null) {
        ensureQosTagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, qosTags_);
        onChanged();
      } else {
        qosTagsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public Builder clearQosTags() {
      if (qosTagsBuilder_ == null) {
        qosTags_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        qosTagsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public Builder removeQosTags(int index) {
      if (qosTagsBuilder_ == null) {
        ensureQosTagsIsMutable();
        qosTags_.remove(index);
        onChanged();
      } else {
        qosTagsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public us.ihmc.aci.ddam.TaggedQoS.Builder getQosTagsBuilder(
        int index) {
      return getQosTagsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public us.ihmc.aci.ddam.TaggedQoSOrBuilder getQosTagsOrBuilder(
        int index) {
      if (qosTagsBuilder_ == null) {
        return qosTags_.get(index);  } else {
        return qosTagsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public java.util.List<? extends us.ihmc.aci.ddam.TaggedQoSOrBuilder> 
         getQosTagsOrBuilderList() {
      if (qosTagsBuilder_ != null) {
        return qosTagsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(qosTags_);
      }
    }
    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public us.ihmc.aci.ddam.TaggedQoS.Builder addQosTagsBuilder() {
      return getQosTagsFieldBuilder().addBuilder(
          us.ihmc.aci.ddam.TaggedQoS.getDefaultInstance());
    }
    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public us.ihmc.aci.ddam.TaggedQoS.Builder addQosTagsBuilder(
        int index) {
      return getQosTagsFieldBuilder().addBuilder(
          index, us.ihmc.aci.ddam.TaggedQoS.getDefaultInstance());
    }
    /**
     * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
     *
     * <pre>
     *list of tags with the associated QoS
     * </pre>
     */
    public java.util.List<us.ihmc.aci.ddam.TaggedQoS.Builder> 
         getQosTagsBuilderList() {
      return getQosTagsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        us.ihmc.aci.ddam.TaggedQoS, us.ihmc.aci.ddam.TaggedQoS.Builder, us.ihmc.aci.ddam.TaggedQoSOrBuilder> 
        getQosTagsFieldBuilder() {
      if (qosTagsBuilder_ == null) {
        qosTagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            us.ihmc.aci.ddam.TaggedQoS, us.ihmc.aci.ddam.TaggedQoS.Builder, us.ihmc.aci.ddam.TaggedQoSOrBuilder>(
                qosTags_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        qosTags_ = null;
      }
      return qosTagsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ddam.TagList)
  }

  // @@protoc_insertion_point(class_scope:ddam.TagList)
  private static final us.ihmc.aci.ddam.TagList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new us.ihmc.aci.ddam.TagList();
  }

  public static us.ihmc.aci.ddam.TagList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TagList>
      PARSER = new com.google.protobuf.AbstractParser<TagList>() {
    public TagList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new TagList(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<TagList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TagList> getParserForType() {
    return PARSER;
  }

  public us.ihmc.aci.ddam.TagList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

