// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qos.proto

package us.ihmc.aci.ddam;

public interface TagListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ddam.TagList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
   *
   * <pre>
   *list of tags with the associated QoS
   * </pre>
   */
  java.util.List<us.ihmc.aci.ddam.TaggedQoS> 
      getQosTagsList();
  /**
   * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
   *
   * <pre>
   *list of tags with the associated QoS
   * </pre>
   */
  us.ihmc.aci.ddam.TaggedQoS getQosTags(int index);
  /**
   * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
   *
   * <pre>
   *list of tags with the associated QoS
   * </pre>
   */
  int getQosTagsCount();
  /**
   * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
   *
   * <pre>
   *list of tags with the associated QoS
   * </pre>
   */
  java.util.List<? extends us.ihmc.aci.ddam.TaggedQoSOrBuilder> 
      getQosTagsOrBuilderList();
  /**
   * <code>repeated .ddam.TaggedQoS qosTags = 1;</code>
   *
   * <pre>
   *list of tags with the associated QoS
   * </pre>
   */
  us.ihmc.aci.ddam.TaggedQoSOrBuilder getQosTagsOrBuilder(
      int index);
}
