// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: topology.proto

package us.ihmc.aci.ddam;

/**
 * Protobuf type {@code ddam.Topology}
 *
 * <pre>
 *topology contains the range of IPs within the subnetwork discovered by the NetSensor
 * </pre>
 */
public  final class Topology extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ddam.Topology)
    TopologyOrBuilder {
  // Use Topology.newBuilder() to construct.
  private Topology(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Topology() {
    networkName_ = "";
    subnetMask_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Topology(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            networkName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            subnetMask_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              internals_ = com.google.protobuf.MapField.newMapField(
                  InternalsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000004;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, us.ihmc.aci.ddam.Host>
            internals = input.readMessage(
                InternalsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            internals_.getMutableMap().put(internals.getKey(), internals.getValue());
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              localGws_ = com.google.protobuf.MapField.newMapField(
                  LocalGwsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000008;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, us.ihmc.aci.ddam.Host>
            localGws = input.readMessage(
                LocalGwsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            localGws_.getMutableMap().put(localGws.getKey(), localGws.getValue());
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              remoteGws_ = com.google.protobuf.MapField.newMapField(
                  RemoteGwsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000010;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, us.ihmc.aci.ddam.Host>
            remoteGws = input.readMessage(
                RemoteGwsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            remoteGws_.getMutableMap().put(remoteGws.getKey(), remoteGws.getValue());
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              externals_ = com.google.protobuf.MapField.newMapField(
                  ExternalsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000020;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, us.ihmc.aci.ddam.Host>
            externals = input.readMessage(
                ExternalsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            externals_.getMutableMap().put(externals.getKey(), externals.getValue());
            break;
          }
          case 66: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timestamp_ != null) {
              subBuilder = timestamp_.toBuilder();
            }
            timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestamp_);
              timestamp_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return us.ihmc.aci.ddam.TopologyProto.internal_static_ddam_Topology_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 4:
        return internalGetInternals();
      case 5:
        return internalGetLocalGws();
      case 6:
        return internalGetRemoteGws();
      case 7:
        return internalGetExternals();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return us.ihmc.aci.ddam.TopologyProto.internal_static_ddam_Topology_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            us.ihmc.aci.ddam.Topology.class, us.ihmc.aci.ddam.Topology.Builder.class);
  }

  private int bitField0_;
  public static final int NETWORKNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object networkName_;
  /**
   * <code>optional string networkName = 1;</code>
   *
   * <pre>
   *a named network segment expressed as a string 
   * </pre>
   */
  public java.lang.String getNetworkName() {
    java.lang.Object ref = networkName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      networkName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string networkName = 1;</code>
   *
   * <pre>
   *a named network segment expressed as a string 
   * </pre>
   */
  public com.google.protobuf.ByteString
      getNetworkNameBytes() {
    java.lang.Object ref = networkName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      networkName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBNETMASK_FIELD_NUMBER = 2;
  private volatile java.lang.Object subnetMask_;
  /**
   * <code>optional string subnetMask = 2;</code>
   *
   * <pre>
   *the subnetmask of this network segment
   * </pre>
   */
  public java.lang.String getSubnetMask() {
    java.lang.Object ref = subnetMask_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subnetMask_ = s;
      return s;
    }
  }
  /**
   * <code>optional string subnetMask = 2;</code>
   *
   * <pre>
   *the subnetmask of this network segment
   * </pre>
   */
  public com.google.protobuf.ByteString
      getSubnetMaskBytes() {
    java.lang.Object ref = subnetMask_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subnetMask_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTERNALS_FIELD_NUMBER = 4;
  private static final class InternalsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, us.ihmc.aci.ddam.Host> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, us.ihmc.aci.ddam.Host>newDefaultInstance(
                us.ihmc.aci.ddam.TopologyProto.internal_static_ddam_Topology_InternalsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.UINT32,
                0,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                us.ihmc.aci.ddam.Host.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, us.ihmc.aci.ddam.Host> internals_;
  private com.google.protobuf.MapField<java.lang.Integer, us.ihmc.aci.ddam.Host>
  internalGetInternals() {
    if (internals_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          InternalsDefaultEntryHolder.defaultEntry);
   }
    return internals_;
  }
  /**
   * <code>map&lt;uint32, .ddam.Host&gt; internals = 4;</code>
   *
   * <pre>
   *a list of internal nodes expressed as Host objects
   * </pre>
   */

  public java.util.Map<java.lang.Integer, us.ihmc.aci.ddam.Host> getInternals() {
    return internalGetInternals().getMap();
  }

  public static final int LOCALGWS_FIELD_NUMBER = 5;
  private static final class LocalGwsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, us.ihmc.aci.ddam.Host> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, us.ihmc.aci.ddam.Host>newDefaultInstance(
                us.ihmc.aci.ddam.TopologyProto.internal_static_ddam_Topology_LocalGwsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.UINT32,
                0,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                us.ihmc.aci.ddam.Host.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, us.ihmc.aci.ddam.Host> localGws_;
  private com.google.protobuf.MapField<java.lang.Integer, us.ihmc.aci.ddam.Host>
  internalGetLocalGws() {
    if (localGws_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          LocalGwsDefaultEntryHolder.defaultEntry);
   }
    return localGws_;
  }
  /**
   * <code>map&lt;uint32, .ddam.Host&gt; localGws = 5;</code>
   *
   * <pre>
   *a list of local gateways expressed as Host objects
   * </pre>
   */

  public java.util.Map<java.lang.Integer, us.ihmc.aci.ddam.Host> getLocalGws() {
    return internalGetLocalGws().getMap();
  }

  public static final int REMOTEGWS_FIELD_NUMBER = 6;
  private static final class RemoteGwsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, us.ihmc.aci.ddam.Host> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, us.ihmc.aci.ddam.Host>newDefaultInstance(
                us.ihmc.aci.ddam.TopologyProto.internal_static_ddam_Topology_RemoteGwsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.UINT32,
                0,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                us.ihmc.aci.ddam.Host.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, us.ihmc.aci.ddam.Host> remoteGws_;
  private com.google.protobuf.MapField<java.lang.Integer, us.ihmc.aci.ddam.Host>
  internalGetRemoteGws() {
    if (remoteGws_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          RemoteGwsDefaultEntryHolder.defaultEntry);
   }
    return remoteGws_;
  }
  /**
   * <code>map&lt;uint32, .ddam.Host&gt; remoteGws = 6;</code>
   *
   * <pre>
   *a list of remote gateways expressed as Host objects
   * </pre>
   */

  public java.util.Map<java.lang.Integer, us.ihmc.aci.ddam.Host> getRemoteGws() {
    return internalGetRemoteGws().getMap();
  }

  public static final int EXTERNALS_FIELD_NUMBER = 7;
  private static final class ExternalsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, us.ihmc.aci.ddam.Host> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, us.ihmc.aci.ddam.Host>newDefaultInstance(
                us.ihmc.aci.ddam.TopologyProto.internal_static_ddam_Topology_ExternalsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.UINT32,
                0,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                us.ihmc.aci.ddam.Host.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, us.ihmc.aci.ddam.Host> externals_;
  private com.google.protobuf.MapField<java.lang.Integer, us.ihmc.aci.ddam.Host>
  internalGetExternals() {
    if (externals_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ExternalsDefaultEntryHolder.defaultEntry);
   }
    return externals_;
  }
  /**
   * <code>map&lt;uint32, .ddam.Host&gt; externals = 7;</code>
   *
   * <pre>
   *a list of external nodes expressed as Host objects
   * </pre>
   */

  public java.util.Map<java.lang.Integer, us.ihmc.aci.ddam.Host> getExternals() {
    return internalGetExternals().getMap();
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 8;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <code>optional .google.protobuf.Timestamp timestamp = 8;</code>
   *
   * <pre>
   *time this object was created
   * </pre>
   */
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <code>optional .google.protobuf.Timestamp timestamp = 8;</code>
   *
   * <pre>
   *time this object was created
   * </pre>
   */
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>optional .google.protobuf.Timestamp timestamp = 8;</code>
   *
   * <pre>
   *time this object was created
   * </pre>
   */
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNetworkNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, networkName_);
    }
    if (!getSubnetMaskBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, subnetMask_);
    }
    for (java.util.Map.Entry<java.lang.Integer, us.ihmc.aci.ddam.Host> entry
         : internalGetInternals().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, us.ihmc.aci.ddam.Host>
      internals = InternalsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      output.writeMessage(4, internals);
    }
    for (java.util.Map.Entry<java.lang.Integer, us.ihmc.aci.ddam.Host> entry
         : internalGetLocalGws().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, us.ihmc.aci.ddam.Host>
      localGws = LocalGwsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      output.writeMessage(5, localGws);
    }
    for (java.util.Map.Entry<java.lang.Integer, us.ihmc.aci.ddam.Host> entry
         : internalGetRemoteGws().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, us.ihmc.aci.ddam.Host>
      remoteGws = RemoteGwsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      output.writeMessage(6, remoteGws);
    }
    for (java.util.Map.Entry<java.lang.Integer, us.ihmc.aci.ddam.Host> entry
         : internalGetExternals().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, us.ihmc.aci.ddam.Host>
      externals = ExternalsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      output.writeMessage(7, externals);
    }
    if (timestamp_ != null) {
      output.writeMessage(8, getTimestamp());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNetworkNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, networkName_);
    }
    if (!getSubnetMaskBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, subnetMask_);
    }
    for (java.util.Map.Entry<java.lang.Integer, us.ihmc.aci.ddam.Host> entry
         : internalGetInternals().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, us.ihmc.aci.ddam.Host>
      internals = InternalsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, internals);
    }
    for (java.util.Map.Entry<java.lang.Integer, us.ihmc.aci.ddam.Host> entry
         : internalGetLocalGws().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, us.ihmc.aci.ddam.Host>
      localGws = LocalGwsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, localGws);
    }
    for (java.util.Map.Entry<java.lang.Integer, us.ihmc.aci.ddam.Host> entry
         : internalGetRemoteGws().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, us.ihmc.aci.ddam.Host>
      remoteGws = RemoteGwsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, remoteGws);
    }
    for (java.util.Map.Entry<java.lang.Integer, us.ihmc.aci.ddam.Host> entry
         : internalGetExternals().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, us.ihmc.aci.ddam.Host>
      externals = ExternalsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, externals);
    }
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getTimestamp());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof us.ihmc.aci.ddam.Topology)) {
      return super.equals(obj);
    }
    us.ihmc.aci.ddam.Topology other = (us.ihmc.aci.ddam.Topology) obj;

    boolean result = true;
    result = result && getNetworkName()
        .equals(other.getNetworkName());
    result = result && getSubnetMask()
        .equals(other.getSubnetMask());
    result = result && internalGetInternals().equals(
        other.internalGetInternals());
    result = result && internalGetLocalGws().equals(
        other.internalGetLocalGws());
    result = result && internalGetRemoteGws().equals(
        other.internalGetRemoteGws());
    result = result && internalGetExternals().equals(
        other.internalGetExternals());
    result = result && (hasTimestamp() == other.hasTimestamp());
    if (hasTimestamp()) {
      result = result && getTimestamp()
          .equals(other.getTimestamp());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + NETWORKNAME_FIELD_NUMBER;
    hash = (53 * hash) + getNetworkName().hashCode();
    hash = (37 * hash) + SUBNETMASK_FIELD_NUMBER;
    hash = (53 * hash) + getSubnetMask().hashCode();
    if (!internalGetInternals().getMap().isEmpty()) {
      hash = (37 * hash) + INTERNALS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetInternals().hashCode();
    }
    if (!internalGetLocalGws().getMap().isEmpty()) {
      hash = (37 * hash) + LOCALGWS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetLocalGws().hashCode();
    }
    if (!internalGetRemoteGws().getMap().isEmpty()) {
      hash = (37 * hash) + REMOTEGWS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetRemoteGws().hashCode();
    }
    if (!internalGetExternals().getMap().isEmpty()) {
      hash = (37 * hash) + EXTERNALS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetExternals().hashCode();
    }
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static us.ihmc.aci.ddam.Topology parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static us.ihmc.aci.ddam.Topology parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.Topology parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static us.ihmc.aci.ddam.Topology parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.Topology parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static us.ihmc.aci.ddam.Topology parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.Topology parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static us.ihmc.aci.ddam.Topology parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static us.ihmc.aci.ddam.Topology parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static us.ihmc.aci.ddam.Topology parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(us.ihmc.aci.ddam.Topology prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ddam.Topology}
   *
   * <pre>
   *topology contains the range of IPs within the subnetwork discovered by the NetSensor
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ddam.Topology)
      us.ihmc.aci.ddam.TopologyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return us.ihmc.aci.ddam.TopologyProto.internal_static_ddam_Topology_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetInternals();
        case 5:
          return internalGetLocalGws();
        case 6:
          return internalGetRemoteGws();
        case 7:
          return internalGetExternals();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableInternals();
        case 5:
          return internalGetMutableLocalGws();
        case 6:
          return internalGetMutableRemoteGws();
        case 7:
          return internalGetMutableExternals();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return us.ihmc.aci.ddam.TopologyProto.internal_static_ddam_Topology_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              us.ihmc.aci.ddam.Topology.class, us.ihmc.aci.ddam.Topology.Builder.class);
    }

    // Construct using us.ihmc.aci.ddam.Topology.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      networkName_ = "";

      subnetMask_ = "";

      internalGetMutableInternals().clear();
      internalGetMutableLocalGws().clear();
      internalGetMutableRemoteGws().clear();
      internalGetMutableExternals().clear();
      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return us.ihmc.aci.ddam.TopologyProto.internal_static_ddam_Topology_descriptor;
    }

    public us.ihmc.aci.ddam.Topology getDefaultInstanceForType() {
      return us.ihmc.aci.ddam.Topology.getDefaultInstance();
    }

    public us.ihmc.aci.ddam.Topology build() {
      us.ihmc.aci.ddam.Topology result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public us.ihmc.aci.ddam.Topology buildPartial() {
      us.ihmc.aci.ddam.Topology result = new us.ihmc.aci.ddam.Topology(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.networkName_ = networkName_;
      result.subnetMask_ = subnetMask_;
      result.internals_ = internalGetInternals();
      result.internals_.makeImmutable();
      result.localGws_ = internalGetLocalGws();
      result.localGws_.makeImmutable();
      result.remoteGws_ = internalGetRemoteGws();
      result.remoteGws_.makeImmutable();
      result.externals_ = internalGetExternals();
      result.externals_.makeImmutable();
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof us.ihmc.aci.ddam.Topology) {
        return mergeFrom((us.ihmc.aci.ddam.Topology)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(us.ihmc.aci.ddam.Topology other) {
      if (other == us.ihmc.aci.ddam.Topology.getDefaultInstance()) return this;
      if (!other.getNetworkName().isEmpty()) {
        networkName_ = other.networkName_;
        onChanged();
      }
      if (!other.getSubnetMask().isEmpty()) {
        subnetMask_ = other.subnetMask_;
        onChanged();
      }
      internalGetMutableInternals().mergeFrom(
          other.internalGetInternals());
      internalGetMutableLocalGws().mergeFrom(
          other.internalGetLocalGws());
      internalGetMutableRemoteGws().mergeFrom(
          other.internalGetRemoteGws());
      internalGetMutableExternals().mergeFrom(
          other.internalGetExternals());
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      us.ihmc.aci.ddam.Topology parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (us.ihmc.aci.ddam.Topology) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object networkName_ = "";
    /**
     * <code>optional string networkName = 1;</code>
     *
     * <pre>
     *a named network segment expressed as a string 
     * </pre>
     */
    public java.lang.String getNetworkName() {
      java.lang.Object ref = networkName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        networkName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string networkName = 1;</code>
     *
     * <pre>
     *a named network segment expressed as a string 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNetworkNameBytes() {
      java.lang.Object ref = networkName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        networkName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string networkName = 1;</code>
     *
     * <pre>
     *a named network segment expressed as a string 
     * </pre>
     */
    public Builder setNetworkName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      networkName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string networkName = 1;</code>
     *
     * <pre>
     *a named network segment expressed as a string 
     * </pre>
     */
    public Builder clearNetworkName() {
      
      networkName_ = getDefaultInstance().getNetworkName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string networkName = 1;</code>
     *
     * <pre>
     *a named network segment expressed as a string 
     * </pre>
     */
    public Builder setNetworkNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      networkName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object subnetMask_ = "";
    /**
     * <code>optional string subnetMask = 2;</code>
     *
     * <pre>
     *the subnetmask of this network segment
     * </pre>
     */
    public java.lang.String getSubnetMask() {
      java.lang.Object ref = subnetMask_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subnetMask_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string subnetMask = 2;</code>
     *
     * <pre>
     *the subnetmask of this network segment
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSubnetMaskBytes() {
      java.lang.Object ref = subnetMask_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subnetMask_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string subnetMask = 2;</code>
     *
     * <pre>
     *the subnetmask of this network segment
     * </pre>
     */
    public Builder setSubnetMask(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      subnetMask_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string subnetMask = 2;</code>
     *
     * <pre>
     *the subnetmask of this network segment
     * </pre>
     */
    public Builder clearSubnetMask() {
      
      subnetMask_ = getDefaultInstance().getSubnetMask();
      onChanged();
      return this;
    }
    /**
     * <code>optional string subnetMask = 2;</code>
     *
     * <pre>
     *the subnetmask of this network segment
     * </pre>
     */
    public Builder setSubnetMaskBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      subnetMask_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, us.ihmc.aci.ddam.Host> internals_;
    private com.google.protobuf.MapField<java.lang.Integer, us.ihmc.aci.ddam.Host>
    internalGetInternals() {
      if (internals_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            InternalsDefaultEntryHolder.defaultEntry);
     }
      return internals_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, us.ihmc.aci.ddam.Host>
    internalGetMutableInternals() {
      onChanged();;
      if (internals_ == null) {
        internals_ = com.google.protobuf.MapField.newMapField(
            InternalsDefaultEntryHolder.defaultEntry);
      }
      if (!internals_.isMutable()) {
        internals_ = internals_.copy();
      }
      return internals_;
    }
    /**
     * <code>map&lt;uint32, .ddam.Host&gt; internals = 4;</code>
     *
     * <pre>
     *a list of internal nodes expressed as Host objects
     * </pre>
     */
    public java.util.Map<java.lang.Integer, us.ihmc.aci.ddam.Host> getInternals() {
      return internalGetInternals().getMap();
    }
    /**
     * <code>map&lt;uint32, .ddam.Host&gt; internals = 4;</code>
     *
     * <pre>
     *a list of internal nodes expressed as Host objects
     * </pre>
     */
    public java.util.Map<java.lang.Integer, us.ihmc.aci.ddam.Host>
    getMutableInternals() {
      return internalGetMutableInternals().getMutableMap();
    }
    /**
     * <code>map&lt;uint32, .ddam.Host&gt; internals = 4;</code>
     *
     * <pre>
     *a list of internal nodes expressed as Host objects
     * </pre>
     */
    public Builder putAllInternals(
        java.util.Map<java.lang.Integer, us.ihmc.aci.ddam.Host> values) {
      getMutableInternals().putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, us.ihmc.aci.ddam.Host> localGws_;
    private com.google.protobuf.MapField<java.lang.Integer, us.ihmc.aci.ddam.Host>
    internalGetLocalGws() {
      if (localGws_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            LocalGwsDefaultEntryHolder.defaultEntry);
     }
      return localGws_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, us.ihmc.aci.ddam.Host>
    internalGetMutableLocalGws() {
      onChanged();;
      if (localGws_ == null) {
        localGws_ = com.google.protobuf.MapField.newMapField(
            LocalGwsDefaultEntryHolder.defaultEntry);
      }
      if (!localGws_.isMutable()) {
        localGws_ = localGws_.copy();
      }
      return localGws_;
    }
    /**
     * <code>map&lt;uint32, .ddam.Host&gt; localGws = 5;</code>
     *
     * <pre>
     *a list of local gateways expressed as Host objects
     * </pre>
     */
    public java.util.Map<java.lang.Integer, us.ihmc.aci.ddam.Host> getLocalGws() {
      return internalGetLocalGws().getMap();
    }
    /**
     * <code>map&lt;uint32, .ddam.Host&gt; localGws = 5;</code>
     *
     * <pre>
     *a list of local gateways expressed as Host objects
     * </pre>
     */
    public java.util.Map<java.lang.Integer, us.ihmc.aci.ddam.Host>
    getMutableLocalGws() {
      return internalGetMutableLocalGws().getMutableMap();
    }
    /**
     * <code>map&lt;uint32, .ddam.Host&gt; localGws = 5;</code>
     *
     * <pre>
     *a list of local gateways expressed as Host objects
     * </pre>
     */
    public Builder putAllLocalGws(
        java.util.Map<java.lang.Integer, us.ihmc.aci.ddam.Host> values) {
      getMutableLocalGws().putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, us.ihmc.aci.ddam.Host> remoteGws_;
    private com.google.protobuf.MapField<java.lang.Integer, us.ihmc.aci.ddam.Host>
    internalGetRemoteGws() {
      if (remoteGws_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            RemoteGwsDefaultEntryHolder.defaultEntry);
     }
      return remoteGws_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, us.ihmc.aci.ddam.Host>
    internalGetMutableRemoteGws() {
      onChanged();;
      if (remoteGws_ == null) {
        remoteGws_ = com.google.protobuf.MapField.newMapField(
            RemoteGwsDefaultEntryHolder.defaultEntry);
      }
      if (!remoteGws_.isMutable()) {
        remoteGws_ = remoteGws_.copy();
      }
      return remoteGws_;
    }
    /**
     * <code>map&lt;uint32, .ddam.Host&gt; remoteGws = 6;</code>
     *
     * <pre>
     *a list of remote gateways expressed as Host objects
     * </pre>
     */
    public java.util.Map<java.lang.Integer, us.ihmc.aci.ddam.Host> getRemoteGws() {
      return internalGetRemoteGws().getMap();
    }
    /**
     * <code>map&lt;uint32, .ddam.Host&gt; remoteGws = 6;</code>
     *
     * <pre>
     *a list of remote gateways expressed as Host objects
     * </pre>
     */
    public java.util.Map<java.lang.Integer, us.ihmc.aci.ddam.Host>
    getMutableRemoteGws() {
      return internalGetMutableRemoteGws().getMutableMap();
    }
    /**
     * <code>map&lt;uint32, .ddam.Host&gt; remoteGws = 6;</code>
     *
     * <pre>
     *a list of remote gateways expressed as Host objects
     * </pre>
     */
    public Builder putAllRemoteGws(
        java.util.Map<java.lang.Integer, us.ihmc.aci.ddam.Host> values) {
      getMutableRemoteGws().putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, us.ihmc.aci.ddam.Host> externals_;
    private com.google.protobuf.MapField<java.lang.Integer, us.ihmc.aci.ddam.Host>
    internalGetExternals() {
      if (externals_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExternalsDefaultEntryHolder.defaultEntry);
     }
      return externals_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, us.ihmc.aci.ddam.Host>
    internalGetMutableExternals() {
      onChanged();;
      if (externals_ == null) {
        externals_ = com.google.protobuf.MapField.newMapField(
            ExternalsDefaultEntryHolder.defaultEntry);
      }
      if (!externals_.isMutable()) {
        externals_ = externals_.copy();
      }
      return externals_;
    }
    /**
     * <code>map&lt;uint32, .ddam.Host&gt; externals = 7;</code>
     *
     * <pre>
     *a list of external nodes expressed as Host objects
     * </pre>
     */
    public java.util.Map<java.lang.Integer, us.ihmc.aci.ddam.Host> getExternals() {
      return internalGetExternals().getMap();
    }
    /**
     * <code>map&lt;uint32, .ddam.Host&gt; externals = 7;</code>
     *
     * <pre>
     *a list of external nodes expressed as Host objects
     * </pre>
     */
    public java.util.Map<java.lang.Integer, us.ihmc.aci.ddam.Host>
    getMutableExternals() {
      return internalGetMutableExternals().getMutableMap();
    }
    /**
     * <code>map&lt;uint32, .ddam.Host&gt; externals = 7;</code>
     *
     * <pre>
     *a list of external nodes expressed as Host objects
     * </pre>
     */
    public Builder putAllExternals(
        java.util.Map<java.lang.Integer, us.ihmc.aci.ddam.Host> values) {
      getMutableExternals().putAll(values);
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 8;</code>
     *
     * <pre>
     *time this object was created
     * </pre>
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 8;</code>
     *
     * <pre>
     *time this object was created
     * </pre>
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 8;</code>
     *
     * <pre>
     *time this object was created
     * </pre>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 8;</code>
     *
     * <pre>
     *time this object was created
     * </pre>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 8;</code>
     *
     * <pre>
     *time this object was created
     * </pre>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
            com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 8;</code>
     *
     * <pre>
     *time this object was created
     * </pre>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 8;</code>
     *
     * <pre>
     *time this object was created
     * </pre>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 8;</code>
     *
     * <pre>
     *time this object was created
     * </pre>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 8;</code>
     *
     * <pre>
     *time this object was created
     * </pre>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ddam.Topology)
  }

  // @@protoc_insertion_point(class_scope:ddam.Topology)
  private static final us.ihmc.aci.ddam.Topology DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new us.ihmc.aci.ddam.Topology();
  }

  public static us.ihmc.aci.ddam.Topology getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Topology>
      PARSER = new com.google.protobuf.AbstractParser<Topology>() {
    public Topology parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new Topology(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<Topology> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Topology> getParserForType() {
    return PARSER;
  }

  public us.ihmc.aci.ddam.Topology getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

