// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linktype.proto

package us.ihmc.aci.test.ddam;

public interface LinkThroughputBoundsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ddam.LinkThroughputBounds)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional double lowerThroughput = 1;</code>
   *
   * <pre>
   *lower bound for the throughput
   * </pre>
   */
  double getLowerThroughput();

  /**
   * <code>optional double throughputStep = 2;</code>
   *
   * <pre>
   *step for the election algorithm
   * </pre>
   */
  double getThroughputStep();
}
