// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prefix.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "prefix.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace netsensor {

namespace {

const ::google::protobuf::EnumDescriptor* Prefix_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_prefix_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_prefix_2eproto() {
  protobuf_AddDesc_prefix_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "prefix.proto");
  GOOGLE_CHECK(file != NULL);
  Prefix_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_prefix_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_prefix_2eproto() {
}

void protobuf_InitDefaults_prefix_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_prefix_2eproto_once_);
void protobuf_InitDefaults_prefix_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_prefix_2eproto_once_,
                 &protobuf_InitDefaults_prefix_2eproto_impl);
}
void protobuf_AddDesc_prefix_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_prefix_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014prefix.proto\022\tnetsensor* \n\006Prefix\022\010\n\004N"
    "ONE\020\000\022\005\n\001K\020\001\022\005\n\001M\020\002B=\n\036us.ihmc.ddam.sens"
    "ors.netsensorB\013PrefixProtoP\001Z\tnetsensor\240"
    "\001\001b\006proto3", 130);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "prefix.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_prefix_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_prefix_2eproto_once_);
void protobuf_AddDesc_prefix_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_prefix_2eproto_once_,
                 &protobuf_AddDesc_prefix_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_prefix_2eproto {
  StaticDescriptorInitializer_prefix_2eproto() {
    protobuf_AddDesc_prefix_2eproto();
  }
} static_descriptor_initializer_prefix_2eproto_;
const ::google::protobuf::EnumDescriptor* Prefix_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Prefix_descriptor_;
}
bool Prefix_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace netsensor

// @@protoc_insertion_point(global_scope)
