MOCKETSDIR = ../../../cpp
UTILDIR = ../../../../util/cpp
EXTERNALS_LIB = ../../../../externals/lib/osx-intel_64
CPP = g++

CPPFLAGS = -g -c -fPIC -DUNIX -DUNIX64 -DOSX -DENABLE_DEBUG -DERROR_CHECKING \
	   -DLITTLE_ENDIAN_SYSTEM -I$(MOCKETSDIR) -I$(UTILDIR) 
LD_FLAGS = ${UTILDIR}/osx/libutil.a -lpthread

sources = ../ARLTestCase ../BasicTest.cpp \
          ../BioEnvMonitoringStation.cpp \
          ../BlockedWriterTest.cpp ../BufferEndlessRecv.cpp \
          ../BufferEndlessSend.cpp ../DataSendReceive.cpp \
          ../DeleteMessageTest.cpp ../FileRecv.cpp \
          ../FileSend.cpp ../FreezeDefrost.cpp ../FreezeDefrostServerSide.cpp \
          ../GatherSendTest.cpp ../IntDataTest.cpp ../IntDataTestUnrelUnseq.cpp \
          ../MessageReplaceTest.cpp ../MigrationFileRec.cpp \
          ../MocketStatusMonitorTest.cpp \
          ../MultipleFreezeDefrost.cpp ../MultipleFreezeDefrostServerSide.cpp \
          ../OneProcessTest.cpp ../Qed.cpp \
          ../QedClient.cpp ../QedClientTest2.cpp \
          ../QedClientTest3.cpp ../QedServer.cpp \
          ../QedServerTest2.cpp ../QedServerTest3.cpp \
          ../QedTest2.cpp ../QedTest3.cpp \
          ../RecvCongestion.cpp \
          ../ReEstablishConnection.cpp \
          ../RemoteStatsTest.cpp \
          ../RetryTimeoutTest.cpp \
          ../RTTClientServerTest.cpp ../RTTEstimator.cpp \
          ../SendCongestion.cpp \
          ../SimultaneousFreezeDefrost.cpp ../SimultaneousFreezeDefrostServerSide.cpp \
          ../SocketClose.cpp \
          ../TestClient.cpp ../TestServer.cpp \
          ../TimeIntervalAverageTest.cpp \
          ../UnreliableSequencedReassemblyTest.cpp
            
           

objects = $(sources:../%.cpp=%.o)

tests = ARLTestCase BasicTest BioEnvMonitoringStation BlockedWriterTest \
        BufferEndlessRecv BufferEndlessSend ClientServerShell DataSendReceive \
        DeleteMessageTest FileRecv FileSend FreezeDefrost FreezeDefrostServerSide GatherSendTest IntDataTest \
        IntDataTestUnrelUnseq MessageReplaceTest MigrationFileRec  MocketStatusMonitorTest \
        MultipleFreezeDefrost MultipleFreezeDefrostServerSide OneProcessTest \
        Qed QedClient QedClientTest2 QedClientTest3 QedServer QedServerTest2 \
        QedServerTest3 QedTest2 QedTest3 RecvCongestion ReEstablishConnection \
        RemoteStatsTest \
        RetryTimeoutTest RTTClientServerTest RTTEstimator SendCongestion \
        SimultaneousFreezeDefrost SimultaneousFreezeDefrostServerSide SocketClose \
        TestClient \
        TestServer TimeIntervalAverageTest UnreliableSequencedReassemblyTest \
	UnreliableSequencedTest
	

all : $(tests)

ARLTestCase : ARLTestCase.o libmockets.a libutil.a libsecurity.a
	$(CPP) -o ARLTestCase ARLTestCase.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

BandwidthControl : BandwidthControl.o libmockets.a
	$(CPP) -o BandwidthControl BandwidthControl.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
        $(LD_FLAGS)

BasicTest : BasicTest.o libmockets.a
	$(CPP) -o BasicTest BasicTest.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

BioEnvMonitoringStation : BioEnvMonitoringStation.o libmockets.a
	$(CPP) -o BioEnvMonitoringStation BioEnvMonitoringStation.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
        $(LD_FLAGS)

BlockedWriterTest : BlockedWriterTest.o libmockets.a
	$(CPP) -o BlockedWriterTest BlockedWriterTest.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)
	
BufferEndlessRecv: BufferEndlessRecv.o libmockets.a
	$(CPP) -o BufferEndlessRecv BufferEndlessRecv.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

BufferEndlessSend: BufferEndlessSend.o libmockets.a
	$(CPP) -o BufferEndlessSend BufferEndlessSend.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)


ClientServerShell : ClientServerShell.o libmockets.a
	$(CPP) -o ClientServerShell ClientServerShell.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

DataSendReceive : DataSendReceive.o libmockets.a
	$(CPP) -o DataSendReceive DataSendReceive.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
        $(LD_FLAGS)

DeleteMessageTest : DeleteMessageTest.o libmockets.a
	$(CPP) -o DeleteMessageTest DeleteMessageTest.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

FileRecv : FileRecv.o libmockets.a
	$(CPP) -o FileRecv FileRecv.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

FileSend : FileSend.o libmockets.a
	$(CPP) -o FileSend FileSend.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

FreezeDefrost : FreezeDefrost.o libmockets.a libutil.a libsecurity.a
	$(CPP) -o FreezeDefrost FreezeDefrost.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/StrClass.cpp \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

FreezeDefrostServerSide : FreezeDefrostServerSide.o libmockets.a libutil.a libsecurity.a
	$(CPP) -o FreezeDefrostServerSide FreezeDefrostServerSide.o \
        $(MOCKETSDIR)/osx/libmockets.a \
        $(UTILDIR)/StrClass.cpp \
        $(UTILDIR)/osx/libsecurity.a \
        $(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
        $(LD_FLAGS)

GatherSendTest : GatherSendTest.o libmockets.a
	$(CPP) -o GatherSendTest GatherSendTest.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

IntDataTest : IntDataTest.o libmockets.a
	$(CPP) -o IntDataTest IntDataTest.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/Socket.cpp \
	$(UTILDIR)/TCPSocket.cpp \
	$(UTILDIR)/StrClass.cpp \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

IntDataTestUnrelUnseq : IntDataTestUnrelUnseq.o libmockets.a
	$(CPP) -o IntDataTestUnrelUnseq IntDataTestUnrelUnseq.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/Socket.cpp \
	$(UTILDIR)/TCPSocket.cpp \
	$(UTILDIR)/StrClass.cpp \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

MessageReplaceTest : MessageReplaceTest.o libmockets.a
	$(CPP) -o MessageReplaceTest MessageReplaceTest.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/Socket.cpp \
	$(UTILDIR)/TCPSocket.cpp \
	$(UTILDIR)/StrClass.cpp \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

MigrationFileRec : MigrationFileRec.o libmockets.a
	$(CPP) -o MigrationFileRec MigrationFileRec.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/Socket.cpp \
	$(UTILDIR)/TCPSocket.cpp \
	$(UTILDIR)/StrClass.cpp \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

MigrationFileSend : MigrationFileSend.o libmockets.a
	make -C $(MOCKETSDIR)/osx clean
	make -f Makefile_debug_migration -C $(MOCKETSDIR)/osx libmockets.a 	
	$(CPP) -o MigrationFileSend MigrationFileSend.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/Socket.cpp \
	$(UTILDIR)/TCPSocket.cpp \
	$(UTILDIR)/StrClass.cpp \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

MocketStatusMonitorTest : MocketStatusMonitorTest.o libmockets.a
	$(CPP) -o MocketStatusMonitorTest MocketStatusMonitorTest.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(LD_FLAGS)

MultipleFreezeDefrost : MultipleFreezeDefrost.o libmockets.a libutil.a libsecurity.a
	$(CPP) -o MultipleFreezeDefrost MultipleFreezeDefrost.o \
        $(MOCKETSDIR)/osx/libmockets.a \
        $(UTILDIR)/StrClass.cpp \
        $(UTILDIR)/osx/libsecurity.a \
        $(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
        $(LD_FLAGS)

MultipleFreezeDefrostServerSide : MultipleFreezeDefrostServerSide.o libmockets.a libutil.a libsecurity.a
	$(CPP) -o MultipleFreezeDefrostServerSide MultipleFreezeDefrostServerSide.o \
        $(MOCKETSDIR)/osx/libmockets.a \
        $(UTILDIR)/StrClass.cpp \
        $(UTILDIR)/osx/libsecurity.a \
        $(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
        $(LD_FLAGS)

OneProcessTest : OneProcessTest.o libmockets.a
	$(CPP) -o OneProcessTest OneProcessTest.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

Qed : Qed.o libmockets.a
	$(CPP) -o Qed Qed.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/Socket.cpp \
	$(UTILDIR)/TCPSocket.cpp \
	$(UTILDIR)/StrClass.cpp \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

QedClient : QedClient.o libmockets.a
	$(CPP) -o QedClient QedClient.o \
	$(MOCKETSDIR)/osx/libmockets.a \
        $(UTILDIR)/Socket.cpp \
        $(UTILDIR)/TCPSocket.cpp \
        $(UTILDIR)/StrClass.cpp \
        $(UTILDIR)/osx/libsecurity.a \
        $(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

QedClientTest2 : QedClientTest2.o libmockets.a
	$(CPP) -o QedClientTest2 QedClientTest2.o \
	$(MOCKETSDIR)/osx/libmockets.a \
        $(UTILDIR)/Socket.cpp \
        $(UTILDIR)/TCPSocket.cpp \
        $(UTILDIR)/StrClass.cpp \
        $(UTILDIR)/osx/libsecurity.a \
        $(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

QedClientTest3 : QedClientTest3.o libmockets.a
	$(CPP) -o QedClientTest3 QedClientTest3.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/Socket.cpp \
        $(UTILDIR)/TCPSocket.cpp \
        $(UTILDIR)/StrClass.cpp \
        $(UTILDIR)/osx/libsecurity.a \
        $(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
        $(LD_FLAGS)

QedServer : QedServer.o libmockets.a
	$(CPP) -o QedServer QedServer.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/Socket.cpp \
        $(UTILDIR)/TCPSocket.cpp \
        $(UTILDIR)/StrClass.cpp \
        $(UTILDIR)/osx/libsecurity.a \
        $(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
        $(LD_FLAGS)

QedServerTest2 : QedServerTest2.o libmockets.a
	$(CPP) -o QedServerTest2 QedServerTest2.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/Socket.cpp \
        $(UTILDIR)/TCPSocket.cpp \
        $(UTILDIR)/StrClass.cpp \
        $(UTILDIR)/osx/libsecurity.a \
        $(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
        $(LD_FLAGS)

QedServerTest3 : QedServerTest3.o libmockets.a
	$(CPP) -o QedServerTest3 QedServerTest3.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/Socket.cpp \
        $(UTILDIR)/TCPSocket.cpp \
        $(UTILDIR)/StrClass.cpp \
        $(UTILDIR)/osx/libsecurity.a \
        $(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
        $(LD_FLAGS)

QedTest2 : QedTest2.o libmockets.a
	$(CPP) -o QedTest2 QedTest2.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/Socket.cpp \
        $(UTILDIR)/TCPSocket.cpp \
        $(UTILDIR)/StrClass.cpp \
        $(UTILDIR)/osx/libsecurity.a \
        $(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
        $(LD_FLAGS)

QedTest3 : QedTest3.o libmockets.a
	$(CPP) -o QedTest3 QedTest3.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/Socket.cpp \
	$(UTILDIR)/TCPSocket.cpp \
	$(UTILDIR)/StrClass.cpp \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

RecvCongestion : RecvCongestion.o libmockets.a
	$(CPP) -o RecvCongestion RecvCongestion.o \
        $(MOCKETSDIR)/osx/libmockets.a \
        $(UTILDIR)/osx/libsecurity.a \
        $(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
        $(LD_FLAGS)

RemoteStatsTest : RemoteStatsTest.o libmockets.a
	$(CPP) -o RemoteStatsTest RemoteStatsTest.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libutil.a \
	$(LD_FLAGS)

RetryTimeoutTest: RetryTimeoutTest.o libmockets.a
	$(CPP) -o RetryTimeoutTest RetryTimeoutTest.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

RTTClientServerTest : RTTClientServerTest.o libmockets.a
	$(CPP) -o RTTClientServerTest RTTClientServerTest.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/StrClass.cpp \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

RTTEstimator : RTTEstimator.o
	$(CPP) -o RTTEstimator RTTEstimator.o \
        $(MOCKETSDIR)/osx/libmockets.a \
        $(UTILDIR)/osx/libsecurity.a \
        $(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
        $(LD_FLAGS)

ReEstablishConnection : ReEstablishConnection.o libmockets.a libutil.a libsecurity.a
	$(CPP) -o ReEstablishConnection ReEstablishConnection.o \
        $(MOCKETSDIR)/osx/libmockets.a \
        $(UTILDIR)/StrClass.cpp \
        $(UTILDIR)/osx/libsecurity.a \
        $(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
        $(LD_FLAGS)


SendCongestion : SendCongestion.o libmockets.a
	$(CPP) -o SendCongestion SendCongestion.o \
        $(MOCKETSDIR)/osx/libmockets.a \
        $(UTILDIR)/osx/libsecurity.a \
        $(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
        $(LD_FLAGS)

SimultaneousFreezeDefrost : SimultaneousFreezeDefrost.o libmockets.a libutil.a libsecurity.a
	$(CPP) -o SimultaneousFreezeDefrost SimultaneousFreezeDefrost.o \
        $(MOCKETSDIR)/osx/libmockets.a \
        $(UTILDIR)/StrClass.cpp \
        $(UTILDIR)/osx/libsecurity.a \
        $(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
        $(LD_FLAGS)

SimultaneousFreezeDefrostServerSide : SimultaneousFreezeDefrostServerSide.o libmockets.a libutil.a libsecurity.a
	$(CPP) -o SimultaneousFreezeDefrostServerSide SimultaneousFreezeDefrostServerSide.o \
        $(MOCKETSDIR)/osx/libmockets.a \
        $(UTILDIR)/StrClass.cpp \
        $(UTILDIR)/osx/libsecurity.a \
        $(UTILDIR)/osx/libutil.a \
        $(EXTERNALS_LIB)/libcrypto.a \
        $(EXTERNALS_LIB)/libssl.a \
        $(LD_FLAGS)

SocketClose : SocketClose.o libmockets.a
	$(CPP) -o SocketClose SocketClose.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(LD_FLAGS)

TestClient : TestClient.o libmockets.a
	$(CPP) -o TestClient TestClient.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

TestServer : TestServer.o libmockets.a
	$(CPP) -o TestServer TestServer.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

TimeIntervalAverageTest : TimeIntervalAverageTest.o libmockets.a libutil.a libsecurity.a
	$(CPP) -o TimeIntervalAverageTest TimeIntervalAverageTest.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

UnreliableSequencedTest : UnreliableSequencedTest.o libmockets.a
	$(CPP) -o UnreliableSequencedTest UnreliableSequencedTest.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)

UnreliableSequencedReassemblyTest : UnreliableSequencedReassemblyTest.o libmockets.a
	$(CPP) -o UnreliableSequencedReassemblyTest UnreliableSequencedReassemblyTest.o \
	$(MOCKETSDIR)/osx/libmockets.a \
	$(UTILDIR)/osx/libsecurity.a \
	$(UTILDIR)/osx/libutil.a \
	$(EXTERNALS_LIB)/libcrypto.a \
	$(EXTERNALS_LIB)/libssl.a \
	$(LD_FLAGS)



libmockets.a :
	(cd ../../../cpp/osx; make -f Makefile.64bit)
libutil.a :
	make -f Makefile.64bit -C $(UTILDIR)/osx libutil.a

libsecurity.a :
	make -f Makefile.64bit -C $(UTILDIR)/osx libsecurity.a

%.o : ../%.cpp
	$(CPP) -c $(CPPFLAGS) $<

clean :
	rm -rf *.o $(tests) MigrationFileSend *.log *.txt
	make -C $(MOCKETSDIR)/osx clean
	make -C $(UTILDIR)/osx clean
	

